### ISSUE TITLE
Text too glitchy

### ISSUE THREAD

**Issue by Dichte-Fichte** [Wruczek/ts-website#165] opened 2020-05-07 11:55 UTC
<img width="396" alt="aw156d6wd1" src="https://user-images.githubusercontent.com/45537786/81291542-3ba7b080-906a-11ea-8f03-26a0f5c43342.PNG">

Tested on 2 Screens. This hurt in some ways my and other eyes.

**Comment by Wruczek** [comment] 2020-05-07 11:59
Can you link your website?

**Comment by Nudelstern** [comment] 2020-05-07 12:01
https://www.cookiecity.eu/bans.php

**Comment by Dichte-Fichte** [comment] 2020-05-07 12:04
https://www.cookiecity.eu/bans.php

**Comment by Wruczek** [comment] 2020-05-07 14:26
If its a problem on a [8k monitor](https://t.me/tswebsite/14023) then I cannot help as I cant reproduce it. Are different pages looking good? Only the text on the banlist is unclear?

**Comment by xopez** [comment] 2020-05-07 15:31
I have the same problem with Firefox and only 1920*1080px
![grafik](https://user-images.githubusercontent.com/28950736/81313685-7b7d9080-9088-11ea-95d2-3acec56260c1.png)
For me it's just the header of the table and only in Firefox.

**Comment by toster234** [comment] 2020-05-07 15:35
Sooo... The problem is with firefox..
![image](https://user-images.githubusercontent.com/26941529/81314080-fb0b5f80-9088-11ea-933c-76f5f39474ee.png)

**Comment by toster234** [comment] 2020-05-07 15:38
More with the font and how the browser processes the font.

**Comment by Wruczek** [comment] 2020-05-07 15:40
@Nudelstern can you check on Chrome?

**Comment by xopez** [comment] 2020-05-07 15:46
Edge Chromium his site (same for my site):
![grafik](https://user-images.githubusercontent.com/28950736/81315438-96e99b00-908a-11ea-8c21-5d4caed29341.png)

**Comment by Wruczek** [comment] 2020-05-19 20:07
I guess its something with firefox? I will close the issue

**Closed as completed** 2020-05-19 20:07 UTC
