### ISSUE TITLE
Exception on cache file loading

### ISSUE THREAD

**Issue by xopez** [Wruczek/ts-website#167] opened 2020-09-13 10:20 UTC
Hello,

i get a few times a day the following error, which i noticed at least in the logs. I don't think that it has very big effects, because the distances to the previous one are usually several hours. Enclosed the error message:

```
2020/09/12 19:29:20 [error] 7337#7337: *54428 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Cannot load cache file! (cachemanager) in /var/www/mightful-noobs.de/private/vendor/wruczek/php-file-cache/src/PhpFileCache.php:75
Stack trace:
#0 /var/www/mightful-noobs.de/private/vendor/wruczek/php-file-cache/src/PhpFileCache.php(313): Wruczek\PhpFileCache\PhpFileCache->loadCacheFile()
#1 /var/www/mightful-noobs.de/private/vendor/wruczek/php-file-cache/src/PhpFileCache.php(62): Wruczek\PhpFileCache\PhpFileCache->reloadFromDisc()
#2 /var/www/mightful-noobs.de/private/php/CacheManager.php(22): Wruczek\PhpFileCache\PhpFileCache->__construct()
#3 /var/www/mightful-noobs.de/private/php/Utils/SingletonTait.php(16): Wruczek\TSWebsite\CacheManager->__construct()
#4 /var/www/mightful-noobs.de/private/php/Utils/SingletonTait.php(26): Wruczek\TSWebsite\CacheManager::Instance()
#5 /var/www/mightful-noobs.de/private/php/AdminStatus.php(55): Wruczek\TSWebsite\CacheManager::i()
#6 /var/www/mightful-noobs.de/private/php/Utils/TemplateUtils.php(109): Wruczek\TS" while reading response header from upstream, client: 164.90.231.0, server: mightful-noobs.de, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "mightful-noobs.de"
```

I have anonymized the IP address.

**Comment by Wruczek** [comment] 2020-09-13 10:22
Yes, this is a issue with the file caching. Duplicate of #158

**Comment by xopez** [comment] 2020-09-13 10:23
Thanks, I didn't see it :)

**Closed as completed by Wruczek** 2020-09-13 10:22 UTC
