### ISSUE TITLE
Update for PHP 8.3.x

### ISSUE THREAD

**Issue by TheChaosToast** [Wruczek/ts-website#226] opened 2024-06-11 18:28 UTC
hello everyone,

are there any plans to run tswebsite on php 8.3.x?

or is there already a way to run it?

thanks

**Comment by toster234** [comment] 2024-06-11 20:14
Duplicate of #221 

Yes there will be support for php 8 soon. At this moment there is no way to implement this because of the problem with ts3phpframework. They update the repo recently but we have to test if everything works properly.

**Closed as not planned by toster234** 2024-06-11 20:14 UTC
Labels: duplicate
