### ISSUE TITLE
Shop

### ISSUE THREAD

**Issue by derrobin154** [Wruczek/ts-website#65] opened 2017-10-18 19:01 UTC
Hello,
I had the idea that you could include a shop where you can collect "coins" through online time etc. and then use them to buy your own channel or icons.

Greetings

**Comment by Wruczek** [comment] 2017-10-18 19:59
Duplicate of #30. Im considering to add it to later versions of ts-website 2.0

**Closed as completed by Wruczek** 2017-10-18 19:59 UTC

**Comment by derrobin154** [comment] 2017-10-21 12:48
#30 says Add a Shop with paypal etc. but i will a other Shop

**Comment by Wruczek** [comment] 2017-10-21 13:02
You can request that under #30 as a additional feature
