### ISSUE TITLE
Adminlist sometimes in Russian Language

### ISSUE THREAD

**Issue by en3rgy97** [Wruczek/ts-website#46] opened 2017-05-28 14:17 UTC
Hello, the Language of the Adminlist is sometimes  different, to the Main Language.
Often the Adminlist is in Russian.

**Comment by toster234** [comment] 2017-05-28 15:53
Thats normal, its cashing. Example if people from russian will come on your site and he have russian language site save cache. And if you load site you see old cache.

**Comment by Wruczek** [comment] 2017-05-28 18:06
Duplicate of #16. Will be fixed in 2.0

**Closed by Wruczek** 2017-05-28 18:06 UTC
